# This is used for scheduled job that is configured on the
# Azure side.

trigger: none

jobs:
  - template: azure-templates.yml
    parameters:
      name: 'Weekly_Stable'

  - template: azure-templates.yml
    parameters:
      name: 'Weekly_Dev'
      astropyCmd: 'pip install git+https://github.com/astropy/astropy.git@master#egg=astropy'
      pytestExtraArgs: '--remote-data'
